### ISSUE TITLE
VCS 兩題建議增加資訊量

### ISSUE THREAD

**Issue by VigaWei** [TW-NCHC/FAQ#33]
VCS 以下兩題FAQ HF建議可以補充資訊量，不知道能否提供 crontab 的操作方法給 user?

:::spoiler Q1. 如何使虛擬運算個體進行自動快照？

:::info

使用 corntab 的方式設定定時的時間，對虛擬運算個體執行快照的功能。

:::

:::spoiler Q2. 如何將虛擬運算中資料定期備份至雲端物件儲存 (COS)？

:::info

使用 corntab 指令碼設定時間、備份資料路徑和雲端物件儲存的目標儲存體，即可完成虛擬運算中資料定時備份。

:::

**Comment by NCHC-InfraServ** [comment]
您可透過 TWCC-CLI 與 `crontab -e` 進行定時快照設定。
- TWCC-CLI 使用詳情請參考 [3-7. 虛擬運算個體快照](https://man.twcc.ai/@twccdocs/twcc-cli-v05#3-7-%E8%99%9B%E6%93%AC%E9%81%8B%E7%AE%97%E5%80%8B%E9%AB%94%E5%BF%AB%E7%85%A7-TBD%E2%80%A6)
- `crontab -e` 請參考 [crontab guru](https://crontab.guru/) 或 [crontab(5) - Linux man page](https://linux.die.net/man/5/crontab)

**Comment by NCHC-InfraServ** [comment]
您可透過 TWCC-CLI 與 `crontab -e` 進行定時快照設定。
- TWCC-CLI 使用詳情請參考 [4-3. 上傳檔案至儲存體](https://man.twcc.ai/@twccdocs/twcc-cli-v05#4-3-%E4%B8%8A%E5%82%B3%E6%AA%94%E6%A1%88%E8%87%B3%E5%84%B2%E5%AD%98%E9%AB%94)
- `crontab -e` 請參考 [crontab guru](https://crontab.guru/) 或 [crontab(5) - Linux man page](https://linux.die.net/man/5/crontab)。
