### ISSUE TITLE
請問 目前 CCS 支援多少種計算環境？

### ISSUE THREAD

**Issue by NCHC-InfraServ** [TW-NCHC/FAQ#37]
as title

**Comment by mawon413** [comment]
在TWCC的容器服務中，提供了14種環境供使用者選擇，包含  
* Tensorflow
* Pytorch
* CUDA
* Matlab
* Caffe
* CNTK
* MXNet
* Caffe2
* TensorRT
* TensorRT_Server
* Theano
* Pytorch
* DIGITS
* RAPIDS

**Comment by NCHC-InfraServ** [comment]
> TWCC 目前是供 14種由 [NGC](https://ngc.nvidia.com/) 提供 TWCC 優化過的計算環境 供使用者選擇
> * Matlab

pre-view 版

如有特殊需求亦可以透過客服人員提出需求。

**Comment by NCHC-InfraServ** [comment]
統計資料

![image](https://user-images.githubusercontent.com/35834182/93455645-378c7900-f90f-11ea-8ee6-01016e54fd70.png)

**Comment by mawon413** [comment]
已併入FAQ

**Comment by mawon413** [comment]
Close issue
