### ISSUE TITLE
如何登入 CCS?

### ISSUE THREAD

**Issue by NCHC-InfraServ** [TW-NCHC/FAQ#38]
as title

**Comment by mawon413** [comment]
請參考下列連結中的"連線使用方式"段落
https://www.twcc.ai/doc?page=container

**Comment by NCHC-InfraServ** [comment]
請參考下列連結中的"[連線使用方式](https://www.twcc.ai/doc?page=container)"段落

**Comment by mawon413** [comment]
已併入FAQ

**Comment by mawon413** [comment]
Close issue
