### ISSUE TITLE
我可以開一個 CCS 給朋友用嗎？

### ISSUE THREAD

**Issue by NCHC-InfraServ** [TW-NCHC/FAQ#39]
as title

**Comment by mawon413** [comment]
開一個容器給他人使用時，需要特別思考以下幾點
* 連線容器會需要您的主機密碼，您的密碼必須給他人
* /home與/work為您的個人HFS檔案區，他人在使用上可能造成這兩個檔案夾中的資料毀損、遺失...等變動，即使您再開新容器也無法復原這些變動

**Comment by NCHC-InfraServ** [comment]
- 分享計算資源會有資料安全的風險，請審慎考慮。
- 你亦可以透過 iService 將使用者加入計畫中，即可自行開設 CCS 資源。

**Comment by mawon413** [comment]
已併入FAQ

**Comment by mawon413** [comment]
Close issue
