### ISSUE TITLE
怎麼使用超級電腦？

### ISSUE THREAD

**Issue by NCHC-InfraServ** [TW-NCHC/FAQ#40]
as title

**Comment by mawon413** [comment]
TWCC中有許多超級電腦的運算資源，您可透過下列方式使用
* 開發型容器: 您可參考此[文件](https://www.twcc.ai/doc?page=container)建立開發型容器
* 高速運算: 您可參考此[文件](https://www.twcc.ai/doc?page=hpc_cli)，連線進入高速運算節點，以command line方式使用高速運算

**Comment by mawon413** [comment]
已併入FAQ

**Comment by mawon413** [comment]
Close
